import Chart from "chart.js/auto";
import 'chartjs-adapter-date-fns';

const ctx = document.getElementById("millisecondsPerDay_Playtime").getContext("2d");

let delayed;

let generatedData = JSON.parse(window.localStorage.getItem("generatedData")); //The Data generated by the web worker

let screenshotsPerDay_Playtime = [];
for (const [key, value] of Object.entries(generatedData.millisecondsPerDay_Playtime))
{//Takes Object, key: unix timestamp, value: amount of milliseconds
    //And makes Array, with every value of the array an object that looks as follows: {x: "yyyy-mm-dd", y: amount of minutes}
    screenshotsPerDay_Playtime.push({x: (new Date(parseInt(key))).toISOString().substring(0, 10), y: value * (1 / 60000)});
}

//Gradient Fill
let gradient = ctx.createLinearGradient(0, 0, 0, 400);
gradient.addColorStop(0, 'rgba(58,123,213,1');
gradient.addColorStop(1, 'rgba(0,210,255,0.3');


const data = {
    datasets: [
        {
            data: screenshotsPerDay_Playtime,
            label: "Amount Of Minutes",
            fill: true,
            backgroundColor: gradient,
            borderColor: "#fff",
            pointBackgroundColor: "#fff",
            tension: 0.4,
        },
    ],
};

const config = {
    type: 'bar',
    data: data,
    options: {
        radius: 5,
        hitRadius: 30,
        hoverRadius: 12,
        responsive: true,
        animation: {
            onComplete: () => {
                delayed = true;
            },
            delay: (context) => {
                let delay = 0;
                if (context.type === "data" && context.mode === "default" && !delayed) {
                    delay = context.dataIndex * 10 + context.dataIndex * 10;
                }
                return delay;
            },
        },
        scales: {
            x: {
                grid: {
                    display: false,
                },
                type: "time",
                time: {
                    unit: 'month',
                },
            },
            y: {
                beginAtZero: true,
                grid: {
                    display: true,
                    color: "#343434"
                },
            },
        },
    },
};

const myChart = new Chart(ctx, config);
