name: Combine PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch: # allows you to manually trigger the workflow

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.0.0 # where X.X.X is the latest version
        with:
          labels: combined-pr # Optional: add a label to the combined PR
